sbmanager:

  ###### GLOBAL #####

  prefix: "&a&lSKYBLOCK &f»"

  #### ADMINCHAT ####

  ytmessage: "&7Zapraszamy na &c&lLIVE&7:"
  hoverytmessage: "&7Kliknij tutaj, aby otworzyć!"
  ### INNE ###
  worldName: "spawn"
